### ISSUE TITLE
Add /pages/Github.cshtml and Github.cshtml.cs

### ISSUE THREAD

**Issue by mheguy** [Refactorio/FactorioWebInterface#2]
Jayefuu:
Using: return Redirect("https://github.com/Refactorio/RedMew/blob/develop/README.md");

I had a go at adding it myself but without fully understanding everything I thought it would save you time to just do it yourself instead of explaining each thing to me ;)

---

grilled:
The scenario button on the homepage <https://redmew.com/> links to <https://github.com/Refactorio/RedMew>.
Indirectly at least. How does that differ?

Maybe we should change the Scenario button to Github, more people wold probably recognise that as what they are looking for.

---

Val:
👍 to changing the "Scenario" Button to "Github"

I agree with grilled https://github.com/Refactorio/RedMew is the proper landing page.

**Comment by grilledham** [comment]
6d58ecfb69c0eabec2b4059f4666cb916c60dd68 changes Scenario button to GitHub and updates the link to <https://github.com/Refactorio/RedMew>
