### ISSUE TITLE
Webhook: Pass repository name as argument

### ISSUE THREAD

**Issue by mheguy** [Refactorio/FactorioWebInterface#29]
I would like to use the same payload URL for updating backend scripts (and one day the server) automatically.

I know there's a `repository.name` property in the JSON payload, and I would have given it a shot if you were deserializing the JSON, but I'm not sure how to find which substring it is or anything like that, so instead I'm opening this issue. :)

**Comment by grilledham** [comment]
I do deserialize the JSON.
The class is <https://github.com/Refactorio/FactorioWebInterface/blob/develop/FactorioWebInterface/Data/GitHub/PushEvent.cs>
In this case I think you are after `Repository.Name`
So something like this
```cs
var push = data.ToObject<PushEvent>();
string name = push.Repository.Name;
```

**Comment by mheguy** [comment]
Ah, guess I totally misunderstood the code. Lol.
