### ISSUE TITLE
Do not reveal the secrets of men

### ISSUE THREAD

**Issue by mheguy** [Refactorio/FactorioWebInterface#3]
In pvp modes the discord bot should not be printing inner-force messages to a public channel.

The bot should be printing shouts and messages from spectators in factorio to discord, and from discord messages should be (and already are) going to all players.

A big caveat at the moment is that the chat logs being available being discord is a very handy moderation tool.

**Comment by grilledham** [comment]
This has been solved.
![image](https://user-images.githubusercontent.com/10003572/58919020-83201100-8724-11e9-9a53-22102eb3a842.png)

Plus all chat is logged to the chat log files now
