### ISSUE TITLE
Server Web GUI Request - Server name limit

### ISSUE THREAD

**Issue by TWLTriston** [Refactorio/FactorioWebInterface#32]
Please limit the server name input box to 50 characters, markup counts as characters and the hard limit can lead to unexpected results.

**Comment by grilledham** [comment]
Done.
![image](https://user-images.githubusercontent.com/10003572/90976159-ae15a100-e532-11ea-92ec-ad1cf21367b6.png)
Limited to 49 characters as that is the actual limit in the server browser lobby.
