### ISSUE TITLE
Mod Pack - Allow Spaces in file names

### ISSUE THREAD

**Issue by TWLTriston** [Refactorio/FactorioWebInterface#35]
https://media.discordapp.net/attachments/361005519185379329/577090196554776576/unknown.png

Mod pack upload-- Squeak Through_1.3.0.zip not allowed to be uploaded.

**Comment by grilledham** [comment]
I don't allow spaces in files / directory names because it seemed like a bad idea. But if mods are going to have spaces in their names, I guess I should relax the rules on spaces.

**Comment by Valansch** [comment]
I seconds grilleds point.
Allowing spaces in file names is the problem not the solution.
If a mod comes with a space in the file name thats on the mod creator to fix their file name.

**Comment by grilledham** [comment]
b6de7f9ad0f27ae7634a7964a87d5968fe856193 allows spaces in mod file names.
I think we have to match the behaviour of the mod portal or else this could become a recurring issue.
