### ISSUE TITLE
Looking to contribute, but the repository is missing a software license.

### ISSUE THREAD

**Issue by AustinTSchaffer** [Refactorio/FactorioWebInterface#42]
Hello,

I stumbled across this repository when I was looking for more information about your custom scenarios. I am running a Factorio server in AWS with a few colleagues, and I'm interested in using these projects to help manage mods, backups, and updates. I'm also interested in trying to build the project for a Linux server and build containers for the installation, so it can be deployed from DockerHub in tandem with a Factorio server container. Unfortunately, since your project does not have a license nor a readme, it's not clear whether I have your permission to fork, clone, build, or use the code.

https://choosealicense.com/no-permission/

Could you please add a license file to clarify your position on this? I don't want to assume your reasoning for making this project open source, but I am interested in using the projects contained in the solution. I am also willing to help with bugs/features and contribute any of the configuration changes upsteam, if you're interested in any of that.

Thanks,
Austin

**Comment by grilledham** [comment]
Hello, thanks for the issue.

I've added a MIT license.

My primary reason for creating the project was as a learning experience. It just happens that we also use the project to run the Redmew servers.

Any PRs would be most welcome. Currently the project isn't very easy to setup and could use some work in that area.

I would be happy to discuss this further on GitHub or the Redmew discord <https://redmew.com/discord>

**Comment by AustinTSchaffer** [comment]
Thanks @grilledham! And thanks for the Discord link. I prefer to chat about smaller bugs and features on GitHub, because I like the organization and visibility of what's currently being discussed, but I'll gladly jump on the Discord if you want to talk about anything in depth.
