### ISSUE TITLE
Mod Pack - Creating new mod pack, destination is initially wrong

### ISSUE THREAD

**Issue by Jayefuu** [Refactorio/FactorioWebInterface#49]
Creating a new mod pack, the destination is wrong the first time you click on it.

Steps:
- Click new
- Give name of new mod pack
- Click on new, empty mod pack
- If you don't know that you have to change the destination, the destination will be set to the latest mod pack, not the new mod pack name. And so I added a bunch of files to seablock without meaning to.
![blah](https://user-images.githubusercontent.com/28716932/64905606-c0f0e600-d6d2-11e9-932b-5b10ad341cce.png)
- When clicking on a new mod pack to add files, the destination dropdown should be set to the correct mod pack.

**Comment by grilledham** [comment]
Maybe this is more of a poor UI design issue.
Destination only applies to copy and move files. So it doesn't make sense to set it to itself.

To be clear Upload should always upload the files to the modpack you have selected.

**Comment by grilledham** [comment]
I renamed the label to `Copy/Move Destination` so hopefully it's clearer now.
