### ISSUE TITLE
silent-command issue

### ISSUE THREAD

**Issue by ProjectSky** [Refactorio/FactorioWebInterface#78]
* Server side use ```silent-command``` cause achievement cannot unlocked.

![image](https://user-images.githubusercontent.com/16351827/92014106-4b69a400-ed81-11ea-9c6c-5aee987c6b4b.png)

**Comment by grilledham** [comment]
This happens becasue the Redmew scenario requires using commands to run properly in multiplayer.
I could look into adding an option to turn off the server using commands.

**Comment by ProjectSky** [comment]
> This happens becasue the Redmew scenario requires using commands to run properly in multiplayer.
> I could look into adding an option to turn off the server using commands.

* I use a custom command to replace silent-command, but i think this not be the best solution

``` lua
local function exec_command(cmd)
  local params = cmd.parameter
  local player = cmd.player_index
  if params and not player then -- isServers?
    local status, err = pcall(function() return loadstring(params)() end )
    if not status then game.print(err) end
  end
end

commands.add_command("exec", "<function> execute lua function, only server can use this command", exec_command)
```
